---
apiVersion: v1
kind: Service
metadata:
  name: jetstream
  labels:
    app: jetstream
  annotations:
    prometheus.io/port: "7777"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: jetstream
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jetstream-config
data:
  jetstream.conf: |
    server_name: $POD_NAME
    port: 4222
    http: 8222
    authorization: {
        token: $AUTH_TOKEN
    }
    max_connections: 64K
    max_payload: 1MB
    max_pending: 64MB
    # unlimited subscription
    max_subscriptions: 0
    cluster {
      name: js-cluster
      listen: 0.0.0.0:6222
      authorization {
        user: route_user
        password: NYm43csaNf34jke32E
        timeout: 0.5
      }
      routes: [
        nats://route_user:NYm43csaNf34jke32E@jetstream-0.jetstream:6222
        nats://route_user:NYm43csaNf34jke32E@jetstream-1.jetstream:6222
        nats://route_user:NYm43csaNf34jke32E@jetstream-2.jetstream:6222
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 10
    }
    jetstream {
      store_dir: /data/jetstream/store
      max_memory_store: 3G
      max_file_store: 100G
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jetstream
  labels:
    app: jetstream
spec:
  selector:
    matchLabels:
      app: jetstream
  serviceName: jetstream
  replicas: 3
  template:
    metadata:
      labels:
        app: jetstream
      annotations:
        prometheus.io/port: metrics
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 30

      containers:
      - name: jetstream
        image: nats:2
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        args:
         - "-js"
         - "-c"
         - "/etc/jetstream-config/jetstream.conf"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).jetstream.$(POD_NAMESPACE).svc
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: jetstream-auth
              key: authtoken
        volumeMounts:
          - name: config-volume
            mountPath: /etc/jetstream-config
          - name: data
            mountPath: /data/jetstream
        resources:
          requests:
            cpu: 0
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
      - name: metrics
        image: natsio/prometheus-nats-exporter:0.12.0
        args:
        - -connz
        - -routez
        - -subz
        - -varz
        - -channelz
        - -serverz
        - http://localhost:8222
        ports:
        - containerPort: 7777
          name: metrics
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "250m"
      volumes:
      - name: config-volume
        configMap:
          name: jetstream-config