auth_enabled: false
chunk_store_config:
  # To avoid querying of data beyond the retention period
  # max_look_back_period must be set to a value less than or equal to 
  # what is set in table_manager.retention_period
  max_look_back_period: 72h
ingester:
  # When this threshold is exceeded the head chunk block will be cut and compressed inside the chunk
  chunk_block_size: 262144
  # How long chunks should sit in-memory with no updates before being flushed 
  # if they don't hit the max block size. This means that half-empty chunks will still be flushed 
  # after a certain period as long as they receive no further activity.
  chunk_idle_period: 3m
  # How long chunks should be retained in-memory after they've been flushed.
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      # The number of ingesters to write to and read from
      replication_factor: 1
  max_transfer_retries: 10
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 48h
schema_config:
  configs:
  - from: "2021-05-17"
    index:
      # Table period
      period: 24h
      prefix: loki_index_
    chunks:
      period: 24h
      prefix: loki_chunks_
    object_store: s3
    schema: v11
    store: boltdb-shipper
storage_config:
  boltdb_shipper:
    # storing BoltDB files locally
    active_index_directory: /loki/index
    # keep keep downloading BoltDB files from shared bucket uploaded by other ingesters to the local cache location
    cache_location: /loki/index_cache
    # keep shipping BoltDB files periodically to the store
    shared_store: s3
  aws:
    s3: s3://XJ2hzpkN:LkYatYm5Ke4BpnQk@minio-hl-svc.minio:9000/loki
    s3forcepathstyle: true
server:
  http_listen_port: 3100
table_manager:
  # The Table Manager implements the retention deleting the entire tables 
  # whose data exceeded the retention_period
  # the Table Manager keeps the last tables alive using this formula:
  # number_of_tables_to_keep = floor(retention_period / table_period) + 1
  retention_deletes_enabled: true
  # The retention period must be a multiple of the index or chunks table period
  retention_period: 72h