apiVersion: v1
data:
  tempo.yaml: |
    # Optional. Setting to true enables multitenancy and requires X-Scope-OrgID header on all requests.
    multitenancy_enabled: false
    compactor:
        compaction:
            block_retention: 144h
            chunk_size_bytes: 1.048576e+07
        ring:
            kvstore:
                store: memberlist
    distributor: {}
    http_api_prefix: ""
    ingester:
        lifecycler:
            ring:
                replication_factor: 3
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
            - gossip-ring.tracing.svc.cluster.local:7946
    overrides:
        # Global ingestion limits configurations
        ingestion_rate_strategy: local
        ingestion_burst_size_bytes: 2e+07
        ingestion_rate_limit_bytes: 2e+07
        max_bytes_per_trace: 3e+07
        max_traces_per_user: 100000
        per_tenant_override_config: /overrides/overrides.yaml
    search_enabled: true
    server:
        http_listen_port: 3200
    storage:
        trace:
            backend: s3
            s3:
                bucket: tempo
                endpoint: minio-hl-svc.minio:9000
                access_key: XJ2hzpkN
                secret_key: LkYatYm5Ke4BpnQk
                insecure: true
kind: ConfigMap
metadata:
  name: tempo-compactor
