apiVersion: apps/v1
kind: Deployment
metadata:
  name: querier
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: querier
      name: querier
      tempo-gossip-member: "true"
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: querier
        name: querier
        tempo-gossip-member: "true"
    spec:
      containers:
      - args:
        - -target=querier
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: grafana/tempo:1.3.1
        imagePullPolicy: IfNotPresent
        name: querier
        ports:
        - containerPort: 3200
          name: prom-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /overrides
          name: overrides
      volumes:
      - configMap:
          name: tempo-querier
        name: tempo-conf
      - configMap:
          name: tempo-overrides
        name: overrides
