apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulture
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vulture
      name: vulture
  template:
    metadata:
      labels:
        app: vulture
        name: vulture
    spec:
      containers:
      - args:
        - -prometheus-listen-address=:8080
        - -tempo-push-url=http://distributor # Default: send to port 14250 (jaeger grpc)
        - -tempo-query-url=http://query-frontend:3200
        - -tempo-org-id=1
        - -tempo-retention-duration=336h
        - -tempo-search-backoff-duration=5s
        - -tempo-read-backoff-duration=10s
        - -tempo-write-backoff-duration=10s
        image: grafana/tempo-vulture:1.5.0
        imagePullPolicy: IfNotPresent
        name: vulture
        ports:
        - containerPort: 8080
          name: prom-metrics
