apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: query-frontend
      name: query-frontend
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: query-frontend
        name: query-frontend
      annotations:
        prometheus.io/port: prom-metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - -target=query-frontend
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: grafana/tempo:1.5.0
        imagePullPolicy: IfNotPresent
        name: query-frontend
        ports:
        - containerPort: 3200
          name: prom-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /overrides
          name: overrides
      - args:
        - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
        - --query.bearer-token-propagation=true
        image: grafana/tempo-query:1.5.0
        imagePullPolicy: IfNotPresent
        name: tempo-query
        ports:
        - containerPort: 16686
          name: jaeger-ui
        - containerPort: 16687
          name: jaeger-metrics
        volumeMounts:
        - mountPath: /conf
          name: tempo-query-conf
      volumes:
      - configMap:
          name: tempo-query
        name: tempo-query-conf
      - configMap:
          name: tempo-overrides
        name: overrides
      - configMap:
          name: tempo-query-frontend
        name: tempo-conf
