apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingester
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: ingester
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
  volumeClaimTemplates:
  - metadata:
      name: ingester-data
      labels:
        app: ingester
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compactor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: compactor
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: distributor
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: querier
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: querier
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: query-frontend
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulture
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: vulture
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi