apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
  labels:
    name: querier
  name: querier
spec:
  ports:
  - name: querier-prom-metrics
    port: 3200
    protocol: TCP
    targetPort: 3200
  selector:
    app: querier
    name: querier
    tempo-gossip-member: "true"