apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - blackbox-exporter-psp
    verbs:
      - use
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blackbox-exporter
subjects:
  - kind: ServiceAccount
    name: blackbox-exporter