---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  - port: 9121
    targetPort: 9121
    name: metrics
  selector:
    app: redis