apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: zookeeper
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
          requests:
            cpu: "0.5"
            memory: 500Mi
  volumeClaimTemplates:
  - metadata:
      name: datadir
      labels:
        app: zk
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 2Gi