apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: loki
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: loki
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi