# config file under /usr/share/kibana/config/kibana.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.16.2
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch.tracing:9200
        ports:
        - containerPort: 5601