apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
spec:
  template:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi