namespace: minio
bases:
- ../base
resources:
- namespace.yaml
patchesStrategicMerge:
- minio-scale8.yaml
secretGenerator:
- name: minio
  literals:
  - accesskey=XJ2hzpkN
  - secretkey=LkYatYm5Ke4BpnQk
