apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  replicas: 8
  template:
    spec:
      containers:
      - name: minio
        args:
        - server
        - --console-address
        - ":9001"
        env:
        - name: MINIO_VOLUMES
          value: "http://minio-{0...7}.minio-hl-svc:9000/export"
        - name: MINIO_SERVER_URL
          value: http://minio-hl-svc.minio:9000
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: minio
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
