namespace: monitoring
resources:
- all-in-one.yaml
- namespace.yaml
- pvc.yaml
patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: prometheus-core
    labelSelector: app=prometheus
secretGenerator:
- name: grafana
  literals:
  - admin-password=admin
  - admin-username=admin