apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-core
spec:
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          limits:
            cpu: 800m
            memory: 5Gi
          requests:
            cpu: 800m
            memory: 5Gi