apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
      annotations:
        prometheus.io/port: prom-metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
        image: otel/opentelemetry-collector:0.66.0
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 50Mi
        ports:
        # see https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md
        # http://localhost:55679/debug/servicez
        # http://localhost:55679/debug/tracez
        - containerPort: 55679 # Default endpoint for ZPages. (http://localhost:55679/debug/servicez)
          name: zpages
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
          name: otel-grpc
        - containerPort: 8888 # Default endpoint for querying metrics.
          name: prom-metrics
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol