apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: traefik
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi