---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  annotations:
    prometheus.io/port: metrics
    prometheus.io/scrape: "true"
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      initContainers:
      - name: copy-scripts
        image: busybox:1.34.1
        command: ['sh', '-c', 'cp /scripts/* /etc/cassandra/']
        volumeMounts:
        - name: config
          mountPath: /etc/cassandra
        - name: scripts
          mountPath: /scripts
      containers:
        - name: cassandra-exporter
          image: criteord/cassandra_exporter:2.3.6
          ports:
          - containerPort: 8080
            name: metrics
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.cassandra.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - cqlsh localhost 9042 -u cassandra -p cassandra
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
            - name: config
              mountPath: /etc/cassandra
      volumes:
        - name: config
          emptyDir: {}
        - name: scripts
          configMap:
            name: cassandra-config
