apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
  - name: metrics
    port: 8080
  selector:
    app: cassandra
