modules:
  tcp_connect:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
  icmp_ping:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
      dont_fragment: true
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: ip4
  http_2xx:
    http:
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s
  http_302:
    http:
      no_follow_redirects: true
      valid_status_codes: [302]
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s
  http_404:
    http:
      no_follow_redirects: false
      valid_status_codes: [404]
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s
  http_401:
    http:
      no_follow_redirects: true
      valid_status_codes: [401]
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s