apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  template:
    spec:
      containers:
      - name: elasticsearch
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 500m
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi