namespace: monitoring
resources:
- all-in-one.yaml
- namespace.yaml
- pvc.yaml
patchesStrategicMerge:
- patch.yaml
secretGenerator:
- name: s3-secret
  literals:
  - accesskey=XJ2hzpkN
  - secretkey=LkYatYm5Ke4BpnQk