namespace: monitoring
resources:
- all-in-one.yaml
- namespace.yaml
- pvc.yaml
patches:
- path: patch.yaml
  target:
    kind: StatefulSet
    name: prometheus-core
    labelSelector: app=prometheus
secretGenerator:
- name: s3-secret
  literals:
  - accesskey=XJ2hzpkN
  - secretkey=LkYatYm5Ke4BpnQk