apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-core
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          limits:
            cpu: 128m
            memory: 256Mi
          requests:
            cpu: 30m
            memory: 32Mi
      - name: thanos
        resources:
          limits:
            cpu: 128m
            memory: 128Mi
          requests:
            cpu: 30m
            memory: 32Mi
      - name: configmap-reload
        resources:
          limits:
            cpu: 30m
            memory: 32Mi
          requests:
            cpu: 30m
            memory: 32Mi
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
      labels:
        app: prometheus
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: thanos
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 30m
            memory: 32Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: thanos
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 30m
            memory: 32Mi
  volumeClaimTemplates:
  - metadata:
      name: thanos-store-data
      labels:
        app: thanos-store-gateway
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-ruler
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: thanos
        resources:
          limits:
            cpu: 512m
            memory: 1Gi
          requests:
            cpu: 30m
            memory: 32Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compactor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: thanos
        resources:
          limits:
            cpu: 128m
            memory: 128Mi
          requests:
            cpu: 30m
            memory: 32Mi