apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-core
spec:
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          limits:
            cpu: 800m
            memory: 5Gi
          requests:
            cpu: 800m
            memory: 5Gi
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
      labels:
        app: prometheus
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi