---
apiVersion: v1
data:
  alert-rules.yaml: |-
    groups:
    - name: Nodes
      rules:
      - alert: HighCPUUsage
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
        expr: |
          (100 - (avg by (instance) (irate(node_cpu_seconds_total{app_kubernetes_io_component="node-exporter",mode="idle"}[5m])) * 100)) > 75
        for: 2m
        labels:
          severity: page
      - alert: NodeLowRootDisk
        annotations:
          summary: "{{$labels.instance}}: Low root disk space"
          description: "{{$labels.instance}}: Root disk usage is above 75% (current value is: {{ $value }})"
        expr: |
          ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"} ) / node_filesystem_size_bytes{mountpoint="/"} * 100) > 75
        for: 2m
        labels:
          severity: page
      - alert: NodeSwapUsage
        annotations:
          summary: "{{$labels.instance}}: Swap usage detected"
          description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"
        expr: |
          (((node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes)/node_memory_SwapTotal_bytes)*100) > 75
        for: 2m
        labels:
          severity: page
      - alert: HighMemoryUsage
        annotations:
          summary: "{{$labels.instance}}: High memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"
        expr: |
          (((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/(node_memory_MemTotal_bytes)*100)) > 75
        for: 2m
        labels:
          severity: page
    - name: Pods
      rules:
      - alert: Container restarted
        annotations:
          summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} was restarted
        expr: |
          sum(increase(kube_pod_container_status_restarts_total{namespace!="kube-system"}[1m])) by (pod,namespace,container) > 0
        for: 0m
        labels:
          severity: warn
      - alert: High Memory Usage of Container 
        annotations: 
          summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of Memory Limit
        expr: | 
          (((sum(container_memory_usage_bytes{image!="", namespace!="kube-system"}) by (namespace,container,pod)  / sum(container_spec_memory_limit_bytes{image!="", namespace!="kube-system"}) by (namespace,container,pod)) * 100) < +Inf) > 75
        for: 5m
        labels:
          severity: warn
      - alert: High CPU Usage of Container 
        annotations: 
          summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of CPU Limit
        expr: | 
          ((sum(irate(container_cpu_usage_seconds_total{image!="", namespace!="kube-system"}[5m])) by (namespace,container,pod) / sum(container_spec_cpu_quota{image!="", namespace!="kube-system"} / container_spec_cpu_period{image!="",namespace!="kube-system"}) by (namespace,container,pod) ) * 100) > 75
        for: 5m
        labels:
          severity: warn
    - name: Instance
      rules:
      - alert: InstanceDown
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
        expr: |
          up == 0
        for: 1m
        labels:
          severity: page
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules