apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://thanos-querier:10902
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
- name: tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://query-frontend.tracing:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo-query