apiVersion: v1
data:
  tempo.yaml: |
    # Optional. Setting to true enables multitenancy and requires X-Scope-OrgID header on all requests.
    multitenancy_enabled: false
    http_api_prefix: ""
    ingester:
      lifecycler:
        ring:
          replication_factor: 3
    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - gossip-ring.tracing.svc.cluster.local:7946
    overrides:
      per_tenant_override_config: /overrides/overrides.yaml
    server:
      http_listen_port: 3200
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: minio-hl-svc.minio:9000
          access_key: XJ2hzpkN
          secret_key: LkYatYm5Ke4BpnQk
          insecure: true
        cache: memcached
        memcached:
          host: memcached.tracing
          max_idle_conns: 16
          consistent_hash: true
          circuit_breaker_consecutive_failures: 10
          circuit_breaker_timeout: 10s
          circuit_breaker_interval: 10s
        pool:
          max_workers: 400
          queue_depth: 20000
kind: ConfigMap
metadata:
  name: tempo-ingester
