apiVersion: apps/v1
kind: Deployment
metadata:
  name: compactor
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: compactor
      name: compactor
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: compactor
        name: compactor
      annotations:
        prometheus.io/port: prom-metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - -target=compactor
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: grafana/tempo:2.0.0
        imagePullPolicy: IfNotPresent
        name: compactor
        ports:
        - containerPort: 3200
          name: prom-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /overrides
          name: overrides
      volumes:
      - configMap:
          name: tempo-compactor
        name: tempo-conf
      - configMap:
          name: tempo-overrides
        name: overrides
