apiVersion: v1
kind: Service
metadata:
  labels:
    name: compactor
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
  name: compactor
spec:
  ports:
  - name: compactor-prom-metrics
    port: 3200
    targetPort: 3200
  selector:
    app: compactor
    name: compactor
