apiVersion: v1
kind: Service
metadata:
  labels:
    name: vulture
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  name: vulture
spec:
  ports:
  - name: vulture-prom-metrics
    port: 8080
    targetPort: 8080
  selector:
    app: vulture
    name: vulture
