apiVersion: v1
kind: Service
metadata:
  labels:
    name: query-frontend
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
  name: query-frontend
spec:
  ports:
  - name: query-frontend-prom-metrics
    port: 3200
    targetPort: 3200
  - name: http
    port: 80
    targetPort: 3200
  selector:
    app: query-frontend
    name: query-frontend
