apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
  labels:
    name: ingester
  name: ingester
spec:
  ports:
  - name: ingester-prom-metrics
    port: 3200
    protocol: TCP
    targetPort: 3200
  selector:
    app: ingester
    name: ingester
    tempo-gossip-member: "true"