apiVersion: v1
kind: Service
metadata:
  labels:
    name: distributor
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
  name: distributor
spec:
  ports:
  - name: distributor-prom-metrics
    port: 3200
    targetPort: 3200
  - name: otel-grpc
    port: 4317
    targetPort: 4317
  - name: otel-http
    port: 4318
    targetPort: 4318
  - name: jaeger-grpc
    port: 14250
    targetPort: 14250
  - name: jaeger-http
    port: 14268
    targetPort: 14268
  selector:
    app: distributor
    name: distributor
    tempo-gossip-member: "true"
