apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stan
spec:
  template:
    spec:
      containers:
      - name: stan
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: stan
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi