apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  serviceName: minio-hl-svc
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  replicas: 0
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      annotations:
        prometheus.io/path: /minio/v2/metrics/cluster
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: minio
        image: docker.io/minio/minio:RELEASE.2023-07-11T21-29-34Z
        args:
        - server
        - /export
        - --console-address
        - ":9001"
        env:
        # allow public access without authentication for prometheus metrics
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_API_ROOT_ACCESS
          value: "on"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
        volumeMounts:
        - mountPath: /export
          name: data

