apiVersion: v1
kind: Service
metadata:
  name: minio-web-svc
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 30080
  selector:
    app: minio