apiVersion: v1
kind: Service
metadata:
  name: minio-web-svc
  labels:
    v1beta1.min.io/instance: minio
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30120
  selector:
    v1beta1.min.io/instance: minio
    app: minio