---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
      annotations:
        prometheus.io/port: metrics
        prometheus.io/scrape: "true"
    spec:
      initContainers:
      - name: increase-vm-max-map
        image: busybox:1.34.1
        command: ["sysctl", "-w", "vm.max_map_count=1048575"]
        securityContext:
          privileged: true
      containers:
        - name: cassandra-exporter
          image: criteord/cassandra_exporter:2.3.6
          ports:
          - containerPort: 8080
            name: metrics
        - name: cassandra
          image: cassandra:4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.cassandra.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - cqlsh localhost 9042 -u cassandra -p cassandra
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
