namespace: cassandra
resources:
- cassandra-sts.yaml
- cassandra-svc.yaml
- namespace.yaml
patches:
- path: patch.yaml
  target:
    kind: StatefulSet
    name: cassandra
    labelSelector: app=cassandra
configMapGenerator:
- name: cassandra-config
  files:
  - cassandra.yaml=configs/cassandra.yaml
  - cassandra-env.sh=configs/cassandra-env.sh
  - cassandra-jaas.config=configs/cassandra-jaas.config
  - cassandra-rackdc.properties=configs/cassandra-rackdc.properties
  - cassandra-topology.properties=configs/cassandra-topology.properties
  - commitlog_archiving.properties=configs/commitlog_archiving.properties
  - cqlshrc.sample=configs/cqlshrc.sample
  - hotspot_compiler=configs/hotspot_compiler
  - jvm11-clients.options=configs/jvm11-clients.options
  - jvm11-server.options=configs/jvm11-server.options
  - jvm8-clients.options=configs/jvm8-clients.options
  - jvm8-server.options=configs/jvm8-server.options
  - jvm-clients.options=configs/jvm-clients.options
  - jvm-server.options=configs/jvm-server.options
  - logback-tools.xml=configs/logback-tools.xml
  - logback.xml=configs/logback.xml
  - metrics-reporter-config-sample.yaml=configs/metrics-reporter-config-sample.yaml
